/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/management.glb -T 
Files: public/models/management.glb [2.3MB] > D:\Melostud - InWork\Freelance\BYPHINE\Website\Dev\3D-for-BYPHINE\management-transformed.glb [156.31KB] (93%)
*/

import React from 'react'
import { useGLTF, Float } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://master--bejewelled-bunny-c31012.netlify.app/models/management-transformed.glb')
  return (
    <Float speed={1} rotationIntensity={2} floatIntensity={5} floatingRange={[0,1]}>
      <group {...props} dispose={null}>
        <mesh castShadow receiveShadow geometry={nodes.Pupille001.geometry} material={materials['Material_0.002']} position={[5.337, 1.253, 1.95]} rotation={[0, 0, -0.27]} scale={0.081} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={materials['Material_1.002']} position={[6.786, -1.52, 2.333]} rotation={[0, 0, -0.27]} scale={[0.081, 0.081, 0.007]} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_0006.geometry} material={materials['Green-Ceramic']} scale={152.257} >
          <meshStandardMaterial color="#FFC200" metalness={0} roughness={0.2} opacity={1} transparent={false}/>
        </mesh>
      </group>
    </Float>

  )
}

useGLTF.preload('https://master--bejewelled-bunny-c31012.netlify.app/models/management-transformed.glb')
