/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://master--bejewelled-bunny-c31012.netlify.app/models/production.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pupille005.geometry}
        material={materials['Material_0.002']}
        position={[1.229, -1.947, 2.007]}
        rotation={[0, 0, -0.08]}
        scale={0.057}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials['Material_1.002']}
        position={[2.593, -3.663, 2.275]}
        rotation={[0, 0, -0.08]}
        scale={[0.057, 0.057, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={materials['Orange  Ceramic']}
        rotation={[0, 0, 0.395]}
        scale={152.257}>
         <meshStandardMaterial color="#FF5400" metalness={0} roughness={0.2} opacity={1} transparent={false}/>
         </mesh>

    </group>
  )
}

useGLTF.preload('https://master--bejewelled-bunny-c31012.netlify.app/models/production.glb')